// Shared catalog data used across marketplace and product detail pages.
const OGG_PRODUCTS = [
  {
    slug: "pommes-golden",
    title: "Pommes Golden",
    subtitle: "Verger du Saleve",
    supplier: "Les vergers Roux",
    location: "Geneve, Suisse",
    category: "Fruits",
    type: "Produit frais",
    distance: "8 km",
    size: "Des 180g",
    price: 1.8,
    unitPrice: "CHF 1.8 / unite",
    badges: ["Bio Suisse", "Prix transparents"],
    mediaClass: "media-apples",
    inStock: true
  },
  {
    slug: "tomates-coeur-de-boeuf",
    title: "Tomates coeur de boeuf",
    subtitle: "Variete ancienne",
    supplier: "Maraichage Dupont",
    location: "Geneve, Suisse",
    category: "Legumes",
    type: "Produit frais",
    distance: "8 km",
    size: "Des 200g",
    price: 2.5,
    unitPrice: "CHF 2.5 / unite",
    badges: ["Bio Suisse", "Prix transparents"],
    mediaClass: "media-tomatoes",
    inStock: true
  },
  {
    slug: "entrecote-maturee",
    title: "Entrecote maturee",
    subtitle: "Boeuf Highland",
    supplier: "Boucherie Muller",
    location: "Geneve, Suisse",
    category: "Viande",
    type: "Viande premium",
    distance: "8 km",
    size: "Des 100 kg",
    price: 45.6,
    unitPrice: "CHF 38.00 / kg",
    badges: ["Bio Suisse", "Prix transparents"],
    mediaClass: "media-steak",
    inStock: true
  },
  {
    slug: "oeufs-fermiers",
    title: "Oeufs fermiers",
    subtitle: "Oeufs plein air calibre M/L",
    supplier: "Ferme des Collines",
    location: "Geneve, Suisse",
    category: "Oeufs",
    type: "Produits fermiers",
    distance: "8 km",
    size: "Des 53 g",
    price: 3.3,
    unitPrice: "CHF 0.55 / unite",
    badges: ["Bio Suisse", "Prix transparents"],
    mediaClass: "media-eggs",
    inStock: true
  },
  {
    slug: "cidre-brut-fermier",
    title: "Cidre brut fermier",
    subtitle: "Cidre artisanal",
    supplier: "Domaine Lefort",
    location: "Geneve, Suisse",
    category: "Liquide",
    type: "Boissons artisanales",
    distance: "8 km",
    size: "Des 33 cl",
    price: 235.2,
    unitPrice: "CHF 9.80 / unite",
    badges: ["Bio Suisse", "Prix transparents"],
    mediaClass: "media-cider",
    inStock: true
  },
  {
    slug: "biscuits-artisanaux",
    title: "Biscuits artisanaux",
    subtitle: "Biscuits au beurre",
    supplier: "Ferme d'Emilie",
    location: "Geneve, Suisse",
    category: "Epicerie seche",
    type: "Snacks",
    distance: "8 km",
    size: "Des 150 g",
    price: 9.5,
    unitPrice: "CHF 9.50 / unite",
    badges: ["Bio Suisse", "Prix transparents"],
    mediaClass: "media-biscuits",
    inStock: true,
    detail: {
      title: "Biscuits artisanaux suisses au beurre",
      description:
        "Decouvrez nos delicieux biscuits artisanaux fabriques avec amour dans notre ferme des Alpes suisses. Prepares avec du beurre fermier bio, de la farine d'epeautre locale et un soupcon de miel de montagne, ces biscuits allient tradition et gourmandise.",
      topTags: ["Bio", "Local", "Suisse", "Certifie Bourgeon"],
      trustBadges: ["Demeter", "IP-SUISSE", "AOC Gruyere", "Certifie Bourgeon"],
      breadcrumb: ["Produits alimentaires", "Biscuits & snacks", "Biscuits artisanaux suisses"],
      stock: "En stock",
      delivery: "Livraison sous 2-3 jours",
      formats: [
        { label: "100g", note: "Format decouverte", priceLabel: "8.50 CHF", active: true },
        { label: "250g", note: "Format classique", priceLabel: "18.90 CHF" },
        { label: "500g", note: "Format familial", priceLabel: "34.50 CHF" },
        { label: "1kg", note: "Format professionnel", priceLabel: "65.00 CHF" }
      ],
      mainPrice: "8.50 CHF",
      mainUnit: "/100g",
      orderNote: "Commande minimale : 10 unites - Remise degressive a partir de 50 unites",
      transparency: [
        { share: "33%", label: "Farine" },
        { share: "19%", label: "Huile d'olive" },
        { share: "48%", label: "Marge & transformation" }
      ],
      producer: {
        name: "Emilie",
        business: "La Ferme d'Emilie",
        location: "Avenches, Vaud",
        website: "www.ferme-emilie.ch",
        tags: ["artisanal", "Engagement durable", "circuit court", "vanille", "suisse"],
        productCount: "24 produits"
      }
    }
  },
  {
    slug: "confiture-fraises",
    title: "Confiture fraises",
    subtitle: "Fraises du jardin",
    supplier: "Confitures Madeleine",
    location: "Geneve, Suisse",
    category: "Conserves",
    type: "Epicerie",
    distance: "8 km",
    size: "Des 200 g",
    price: 7.2,
    unitPrice: "CHF 7.20 / bocal",
    badges: ["Bio Suisse", "Prix transparents"],
    mediaClass: "media-jam",
    inStock: true
  },
  {
    slug: "tomme-de-savoie-aop",
    title: "Tomme de Savoie AOP",
    subtitle: "Affinage 3 mois",
    supplier: "Fromagerie Blanc",
    location: "Geneve, Suisse",
    category: "Fromages",
    type: "Laitier",
    distance: "8 km",
    size: "Des 100 g",
    price: 2.8,
    unitPrice: "CHF 28.0 / kg",
    badges: ["Bio Suisse", "Prix transparents"],
    mediaClass: "media-cheese",
    inStock: true
  },
  {
    slug: "pain-au-levain",
    title: "Pain au levain",
    subtitle: "Levain naturel",
    supplier: "Ferme d'Emilie",
    location: "Geneve, Suisse",
    category: "Pain",
    type: "Boulangerie",
    distance: "8 km",
    size: "Des 400 g",
    price: 5.9,
    unitPrice: "CHF 5.90 / unite",
    badges: ["Bio Suisse", "Prix transparents"],
    mediaClass: "media-bread",
    inStock: true
  },
  {
    slug: "grains-de-cafe-equitables",
    title: "Grains de cafe equitables",
    subtitle: "Produits laitiers",
    supplier: "Cafe du Leman SA",
    location: "Geneve, Suisse",
    category: "Boissons",
    type: "Boissons",
    distance: "8 km",
    size: "Des 250 g",
    price: 7.5,
    unitPrice: "CHF 7.50 / unite",
    badges: ["Bio Suisse", "Prix transparents"],
    mediaClass: "media-coffee",
    inStock: true
  },
  {
    slug: "yaourt-biologique-suisse",
    title: "Yaourt biologique suisse",
    subtitle: "Yaourt",
    supplier: "Ferme d'Emilie",
    location: "Geneve, Suisse",
    category: "Produits laitier",
    type: "Laitier",
    distance: "10 km",
    size: "Des 150 g",
    price: 7.5,
    unitPrice: "CHF 7.50 / unite",
    badges: ["Bio Suisse", "Prix transparents"],
    mediaClass: "media-yogurt",
    inStock: true
  }
];
